syntax = "proto3";

package temporal.api.sdk.v1;

option go_package = "go.temporal.io/api/sdk/v1;sdk";
option java_package = "io.temporal.api.sdk.v1";
option java_multiple_files = true;
option java_outer_classname = "UserMetadataProto";
option ruby_package = "Temporalio::Api::Sdk::V1";
option csharp_namespace = "Temporalio.Api.Sdk.V1";


import "temporal/api/common/v1/message.proto";
import "temporalvalidate/v1/annotations.proto";

// Information a user can set, often for use by user interfaces.
message UserMetadata {
  // Summary for user interfaces. Use a json/plain payload with one JSON string.
  // The default serialized size limit is 400 bytes.
  temporal.api.common.v1.Payload summary = 1 [(temporalvalidate.v1.field_coverage_ignored) = "ValidateUserMetadata checks the summary size"];

  // Details for user interfaces. Use a json/plain payload with one JSON string.
  // The default serialized size limit is 20000 bytes.
  temporal.api.common.v1.Payload details = 2 [(temporalvalidate.v1.field_coverage_ignored) = "ValidateUserMetadata checks the details size"];
}
